development:
  client_id: f69d548aeb314c2997583b8cfa154691
  client_secret: e9b4325f69af428b91d6ee229d5578ca
  redirect_uri: http://127.0.0.1:3000/user/
  meta_keywords: "Joyviewer, Joyviewer.com, instagram, IG, web, PC, Computer, viewer"
  meta_description: "Joy of Instagram On Web"
  fb_app_id: 461403163888029
production:
  client_id: d8d1ad02f4564390aaac77be8390c6a6
  redirect_uri: http://Joyviewer.com/user/
  meta_keywords: "Joyviewer, Joyviewer.com, instagram, IG, web, PC, Computer, viewer"
  meta_description: "Joy of Instagram On Web"